// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2002/B 1000 2026.5.13
// https://codeforces.com/problemset/status/2002/problem/B?friends=on
func Test_cf2002B(t *testing.T) {
	testCases := [][2]string{
		{
			`2
2
1 2
1 2
3
1 2 3
2 3 1`,
			`Bob
Alice`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2002B)
}
