// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2004/C 1100 2026.5.14
// https://codeforces.com/problemset/status/2004/problem/C?friends=on
func Test_cf2004C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2 5
1 10
3 0
10 15 12
4 6
3 1 2 4
2 4
6 9`,
			`4
13
0
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2004C)
}
