// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc402/tasks/abc402_e ~CF1777 1409
// 提交：https://atcoder.jp/contests/abc402/submit?taskScreenName=abc402_e
// 对拍：https://atcoder.jp/contests/abc402/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc402_e&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc402/submissions?f.Status=AC&f.Task=abc402_e&orderBy=source_length
func Test_e(t *testing.T) {
	testCases := [][2]string{
		{
			`3 2
100 1 50
200 1 20
1000 1 1`,
			`95`,
		},
		{
			`2 7
100 3 50
100 2 50`,
			`125`,
		},
		{
			`5 32
500 9 57
300 4 8
300 3 32
300 7 99
100 8 69`,
			`953.976967020096`,
		},
		{
			`7 78
100 1 100
200 2 90
300 3 80
400 4 60
450 5 50
525 6 30
650 7 1`,
			`1976.2441416041121021`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
