// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1303/E 2200 2026.5.7
// https://codeforces.com/problemset/status/1303/problem/E?friends=on
func Test_cf1303E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
ababcd
abcba
a
b
defi
fed
xyz
x`,
			`YES
NO
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1303E)
}
