// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1142/B 2000 2026.5.9
// https://codeforces.com/problemset/status/1142/problem/B?friends=on
func Test_cf1142B(t *testing.T) {
	testCases := [][2]string{
		{
			`3 6 3
2 1 3
1 2 3 1 2 3
1 5
2 6
3 5`,
			`110`,
		},
		{
			`2 4 3
2 1
1 1 2 2
1 2
2 3
3 4`,
			`010`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1142B)
}
