// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1221/E 2500 2026.5.15
// https://codeforces.com/problemset/status/1221/problem/E?friends=on
func Test_cf1221E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3 2
XX......XX...X
4 2
X...X.X..X
5 3
.......X..X`,
			`YES
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1221E)
}
