// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1285/F 2900 2026.5.12
// https://codeforces.com/problemset/status/1285/problem/F?friends=on
func Test_cf1285F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
13 35 77`,
			`1001`,
		},
		{
			`6
1 2 4 8 16 32`,
			`32`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1285F)
}
