// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1743/C 1100 2026.5.9
// https://codeforces.com/problemset/status/1743/problem/C?friends=on
func Test_cf1743C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5
01110
10 5 8 9 6
6
011011
20 10 9 30 20 19
4
0000
100 100 100 100
4
0111
5 4 5 1`,
			`27
80
0
14`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1743C)
}
