// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1792/F1 2900 2026.5.9
// https://codeforces.com/problemset/status/1792/problem/F1?friends=on
func Test_cf1792F2(t *testing.T) {
	testCases := [][2]string{
		{
			`3`,
			`6`,
		},
		{
			`4`,
			`50`,
		},
		{
			`100`,
			`878752271`,
		},
		{
			`1337`,
			`520628749`,
		},
		{
			`42013`,
			`906821221`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1792F1)
}
