// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1965/A 1400 2026.5.11
// https://codeforces.com/problemset/status/1965/problem/A?friends=on
func Test_cf1965A(t *testing.T) {
	testCases := [][2]string{
		{
			`7
5
3 3 3 3 3
2
1 7
7
1 3 9 7 4 2 100
3
1 2 3
6
2 1 3 4 2 4
8
5 7 2 9 6 3 3 2
1
1000000000`,
			`Alice
Bob
Alice
Alice
Bob
Alice
Alice`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1965A)
}
