// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1980/F2 2400 2026.5.12
// https://codeforces.com/problemset/status/1980/problem/F2?friends=on
func Test_cf1980F2(t *testing.T) {
	testCases := [][2]string{
		{
			`5
2 2 3
1 1
1 2
2 2
5 5 4
1 2
2 2
3 4
4 3
2 5 9
1 2
1 5
1 1
2 2
2 4
2 5
1 4
2 3
1 3
6 4 4
6 2
1 3
1 4
1 2
3 4 5
2 1
3 2
1 4
1 3
2 4`,
			`1
1 0 1 
11
0 1 0 4 
1
0 0 1 1 0 0 0 0 0 
6
15 0 0 0 
1
2 3 0 0 0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1980F2)
}
