// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1993/F2 2800 2026.5.9
// https://codeforces.com/problemset/status/1993/problem/F2?friends=on
func Test_cf1993F2(t *testing.T) {
	testCases := [][2]string{
		{
			`6
2 4 2 2
UR
4 2 1 1
LLDD
6 3 3 1
RLRRRL
5 6 3 3
RUURD
7 5 3 4
RRDLUUU
7 123456789999 3 2
ULULURD`,
			`1
4
3
1
1
41152263332`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1993F2)
}
