// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/982/E 2600 2026.5.12
// https://codeforces.com/problemset/status/982/problem/E?friends=on
func Test_cf982E(t *testing.T) {
	testCases := [][2]string{
		{
			`4 3 2 2 -1 1`,
			`0 0`,
		},
		{
			`4 4 2 0 1 1`,
			`-1`,
		},
		{
			`10 10 10 1 -1 0`,
			`-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf982E)
}
