// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1805/D 1800 2026.5.6
// https://codeforces.com/problemset/status/1805/problem/D?friends=on
func Test_cf1805D(t *testing.T) {
	testCases := [][2]string{
		{
			`6
1 2
1 3
2 4
2 5
3 6`,
			`1 1 2 4 6 6`,
		},
		{
			`5
1 2
2 3
3 4
3 5`,
			`1 1 3 5 5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1805D)
}
