// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1805/F2 3100 2026.5.5
// https://codeforces.com/problemset/status/1805/problem/F2?friends=on
func Test_cf1805F2(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 2 4 5 6`,
			`34`,
		},
		{
			`9
1 1 1 7 7 7 9 9 9`,
			`256`,
		},
		{
			`7
1 7 9 2 0 0 9`,
			`20`,
		},
		{
			`3
1000000000 1000000000 777`,
			`1540`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1805F2)
}
