// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/841/B 1100 2026.5.14
// https://codeforces.com/problemset/status/841/problem/B?friends=on
func Test_cf841B(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 3 2 3`,
			`First`,
		},
		{
			`2
2 2`,
			`Second`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf841B)
}
