// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2200/E 1500 2026.5.11
// https://codeforces.com/problemset/status/2200/problem/E?friends=on
func Test_cf2200E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
10
10 9 8 7 6 5 4 3 2 1
3
1 8192 677
2
6 5
2
6 7`,
			`Alice
Bob
Alice
Bob`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2200E)
}
