// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1658/E 2500 2026.5.15
// https://codeforces.com/problemset/status/1658/problem/E?friends=on
func Test_cf1658E(t *testing.T) {
	testCases := [][2]string{
		{
			`3 1
1 2 4
6 8 3
9 5 7`,
			`GGG
MGG
MGG`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1658E)
}
