// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc403/tasks/abc403_d 1052
// 提交：https://atcoder.jp/contests/abc403/submit?taskScreenName=abc403_d
// 对拍：https://atcoder.jp/contests/abc403/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc403_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc403/submissions?f.Status=AC&f.Task=abc403_d&orderBy=source_length
func Test_d(t *testing.T) {
	testCases := [][2]string{
		{
			`5 2
3 1 4 1 5`,
			`1`,
		},
		{
			`4 3
1 6 1 8`,
			`0`,
		},
		{
			`10 3
1 6 2 10 2 3 2 10 6 4`,
			`2`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
