// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc369/tasks/abc369_f ~CF1935 1618
// 提交：https://atcoder.jp/contests/abc369/submit?taskScreenName=abc369_f
// 对拍：https://atcoder.jp/contests/abc369/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc369_f&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc369/submissions?f.Status=AC&f.Task=abc369_f&orderBy=source_length
func Test_f(t *testing.T) {
	testCases := [][2]string{
		{
			`3 4 4
3 3
2 1
2 3
1 4`,
			`3
DRRDR`,
		},
		{
			`2 2 2
2 1
1 2`,
			`1
DR`,
		},
		{
			`10 15 8
2 7
2 9
7 9
10 3
7 11
8 12
9 6
8 1`,
			`5
DRRRRRRRRDDDDDRRDRDDRRR`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
